### ISSUE TITLE
TypeError: unhashable type: 'dict' if functools32 is installed

### ISSUE THREAD

**Issue by bagage** [Phyks/Flatisfy#4]
If you have functools32 installed (python-functools32 on debian), then `fetch` command will abort:

```
$  python2 -m flatisfy fetch --config config.json
... 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gautier/code/docker/flatisfy/Flatisfy/flatisfy/__main__.py", line 220, in <module>
    main()
  File "/home/gautier/code/docker/flatisfy/Flatisfy/flatisfy/__main__.py", line 178, in main
    fetch_details=True)["new"]
  File "flatisfy/cmds.py", line 121, in filter_fetched_flats
    fetch_details
  File "flatisfy/cmds.py", line 62, in filter_flats_list
    config)
  File "flatisfy/tools.py", line 311, in wrapped
    res = f(*args, **kwargs)
  File "flatisfy/filters/__init__.py", line 113, in first_pass
    flats_list = metadata.guess_postal_code(flats_list, constraint, config)
  File "flatisfy/filters/metadata.py", line 139, in guess_postal_code
    "postal_codes": data.load_data(PostalCode, constraint, config)
  File "/usr/lib/python2.7/dist-packages/functools32/functools32.py", line 394, in wrapper
    result = cache[key]
TypeError: unhashable type: 'dict'
```

**Comment by Phyks** [comment]
Should be fixed by https://github.com/Phyks/Flatisfy/commit/7e35b71c28c84053c58c2b8f5b41c130d1243cf0.

Good catch, the API of `data.load_data` changed recently, and we missed to test it out with `functools` installed! Thanks a lot for the reporting!
