### ISSUE TITLE
Error if invalid postal code in config

### ISSUE THREAD

**Issue by bagage** [Phyks/Flatisfy#5]
If you set only one constraint with invalid postal code such as `"postal_codes": ["69000"]` (69000 isn't a valid one), it will crash with:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gautier/code/docker/flatisfy/Flatisfy/flatisfy/__main__.py", line 220, in <module>
    main()
  File "/home/gautier/code/docker/flatisfy/Flatisfy/flatisfy/__main__.py", line 210, in main
    cmds.import_and_filter(config, load_from_db=False)
  File "flatisfy/cmds.py", line 143, in import_and_filter
    fetch_details=(not load_from_db))
  File "flatisfy/cmds.py", line 121, in filter_fetched_flats
    fetch_details
  File "flatisfy/cmds.py", line 62, in filter_flats_list
    config)
  File "flatisfy/tools.py", line 311, in wrapped
    res = f(*args, **kwargs)
  File "flatisfy/filters/__init__.py", line 113, in first_pass
    flats_list = metadata.guess_postal_code(flats_list, constraint, config)
  File "flatisfy/filters/metadata.py", line 210, in guess_postal_code
    for constraint_postal_code in constraint["postal_codes"]
ValueError: min() arg is an empty sequence
```

**Comment by Phyks** [comment]
Should be fixed by the above commit. Thanks for reporting!
