### ISSUE TITLE
App doesn't support python3 ?

### ISSUE THREAD

**Issue by flyingrub** [Phyks/Flatisfy#8]
```
(flatisfy) ➜  flatisfy git:(master) ✗ python -m flatisfy build-data --config config.json
ERROR:flatisfy.config:Unable to load configuration from file, using default configuration: Expecting value: line 39 column 20 (char 845).
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fly/workspace/flatisfy/flatisfy/__main__.py", line 226, in <module>
    main()
  File "/home/fly/workspace/flatisfy/flatisfy/__main__.py", line 145, in main
    config = flatisfy.config.load_config(args)
  File "/home/fly/workspace/flatisfy/flatisfy/config.py", line 272, in load_config
    config_validation = validate_config(config_data)
  File "/home/fly/workspace/flatisfy/flatisfy/config.py", line 127, in validate_config
    assert config["smtp_server"] is None or isinstance(config["smtp_server"], (str, unicode))  # noqa: E501
NameError: name 'unicode' is not defined
```

**Comment by Phyks** [comment]
In principle, the codebase should be almost `python3`-compatible. Still, there may be issues from place to place with Python3, such as this one.

Problem is: Weboob was not working with Python3 when I started coding this, and many housing modules are not yet ported to Python 3. So I'm not sure it will be 100% usable with Python3. Still, Flatisfy codebase should be Python3-compatible, and this is a relevant issue.

**Comment by Phyks** [comment]
Should be fixed in https://github.com/Phyks/Flatisfy/commit/c96b2a3f4c561bb750c3c768463564a607a1783d.
